### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by loganharbour**
Gets things ready for use, primarily in CI.

### CODE REVIEW

**Comment by loganharbour** [comment]
@cticenhour do you want to setup sqa here or in another PR?

**Comment by cticenhour** [comment]
Good idea - let's set it up here too. I'll work on it this morning.

**Comment by loganharbour** [comment]
Sounds good. Let me fix the coverage content and add the EM+RT module and then its good for you

**Review by loganharbour — COMMENTED** [review]
Good with the content that isn't my own. Coverage will resolve itself on devel as we're missing the first base coverage data.

**Review by cticenhour — APPROVED** [review]
Approval of commits that are not my own.

**Pull request merged**
